<?php
session_start();
require 'db_connect.php';
require 'vendor/autoload.php'; // or 'dompdf/autoload.inc.php'

use Dompdf\Dompdf;
use Dompdf\Options;

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'officer') {
    die("Unauthorized access.");
}

if (!isset($_GET['fine_id'])) {
    die("Fine ID missing.");
}

$fine_id = $_GET['fine_id'];
$officer_id = $_SESSION['user_id'];

// ✅ Fetch officer info
$officerStmt = $pdo->prepare("SELECT name, email FROM users WHERE user_id = ?");
$officerStmt->execute([$officer_id]);
$officer = $officerStmt->fetch(PDO::FETCH_ASSOC);

// ✅ Fetch the single fine
$stmt = $pdo->prepare("SELECT * FROM fines WHERE fine_id = ? AND officer_id = ?");
$stmt->execute([$fine_id, $officer_id]);
$fine = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$fine) {
    die("Fine not found or access denied.");
}

// ✅ Build PDF content
$html = '
<style>
    body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #333; padding: 20px; }
    h2, h4 { text-align: center; color: #2b7cff; margin-bottom: 5px; }
    .section { border: 1px solid #ccc; padding: 10px 15px; border-radius: 8px; margin-bottom: 15px; background-color: #f9f9f9; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { padding: 8px; text-align: left; }
    th { width: 30%; color: #2b7cff; }
    .footer { text-align: center; font-size: 11px; margin-top: 30px; color: #777; }
</style>

<h2>FineMate Official Record</h2>
<h4>Fine Details Report</h4>
<hr>

<div class="section">
    <h4>Officer Details</h4>
    <p><strong>Name:</strong> ' . htmlspecialchars($officer['name']) . '</p>
    <p><strong>Email:</strong> ' . htmlspecialchars($officer['email']) . '</p>
    <p><strong>Date Generated:</strong> ' . date("Y-m-d H:i:s") . '</p>
</div>

<div class="section">
    <h4>Fine Details</h4>
    <table>
        <tr><th>Offender Name:</th><td>' . htmlspecialchars($fine['offender_name']) . '</td></tr>
        <tr><th>NIC:</th><td>' . htmlspecialchars($fine['offender_nic']) . '</td></tr>
        <tr><th>License No:</th><td>' . htmlspecialchars($fine['offender_license_no']) . '</td></tr>
        <tr><th>Vehicle No:</th><td>' . htmlspecialchars($fine['vehicle_no']) . '</td></tr>
        <tr><th>Fine Type:</th><td>' . htmlspecialchars($fine['fine_type']) . '</td></tr>
        <tr><th>Fine Amount (Rs):</th><td>' . number_format($fine['fine_amount'], 2) . '</td></tr>
        <tr><th>Fine Date:</th><td>' . htmlspecialchars($fine['fine_date']) . '</td></tr>
        <tr><th>Fine Time:</th><td>' . htmlspecialchars($fine['fine_time']) . '</td></tr>
        <tr><th>Location:</th><td>' . htmlspecialchars($fine['fine_location']) . '</td></tr>
        <tr><th>Weather:</th><td>' . htmlspecialchars($fine['weather']) . '</td></tr>
        <tr><th>Payment Status:</th><td>' . htmlspecialchars($fine['payment_status']) . '</td></tr>
        <tr><th>Due Date:</th><td>' . htmlspecialchars($fine['due_date']) . '</td></tr>
        <tr><th>Remarks:</th><td>' . htmlspecialchars($fine['remarks']) . '</td></tr>
    </table>
</div>

<div class="footer">
    Generated by FineMate © ' . date("Y") . '
</div>
';

// ✅ Generate the PDF
$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isRemoteEnabled', true);

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// ✅ Output
$filename = "Fine_#" . $fine['fine_id'] . "_" . date('Ymd_His') . ".pdf";
$dompdf->stream($filename, ["Attachment" => true]);
exit;
?>
